// Confirms the accessibility patch and the current feature set compiled in.
// Markers must SURVIVE COMPILATION - GML comments do not, and object references are
// rendered numerically, so check for code and string literals only.
using System;
using UndertaleModLib.Models;

EnsureDataLoaded();

var ctx = new GlobalDecompileContext(Data);
var settings = Data.ToolInfo.DecompilerSettings;
var controller = Data.GameObjects.ByName("Controller");

string Dec(UndertaleCode c) =>
    new Underanalyzer.Decompiler.DecompileContext(ctx, c, settings).DecompileToString();

var create = Dec(controller.EventHandlerFor(EventType.Create, Data));
var step = Dec(controller.EventHandlerFor(EventType.Step, EventSubtypeStep.Step, Data));
var infoObj = Data.GameObjects.ByName("Info");
var infoDrawCode = infoObj?.EventHandlerFor(EventType.Draw, EventSubtypeDraw.Draw, Data);
var infoDraw = infoDrawCode != null ? Dec(infoDrawCode) : "";
var escCode = controller.EventHandlerFor(EventType.KeyPress, (uint)27, Data);
var escape = escCode != null ? Dec(escCode) : "";
var all = create + "\n" + step + "\n" + infoDraw + "\n" + escape;

Console.WriteLine($"Create {create.Length} chars, Step {step.Length} chars, Info Draw {infoDraw.Length} chars");
Console.WriteLine($"VarCount1 (must be 0): {Data.VarCount1}");
Console.WriteLine();

var checks = new (string label, string needle, bool wantPresent)[]
{
    ("patch present",             "a11y_ready",            true),
    ("no globals introduced",     "global.a11y",           false),
    ("no array indexing",         "a11y_ins[",             false),
    ("inert-title guard",         "BLOCK_EXIT",            true),
    ("credits screen",            "@credits",              true),
    ("Back vs Resume",            "Lvl_Main_Menu",         true),
    ("slider: sound volume",      "Sound Volume",          true),
    ("slider: music volume",      "Music Volume",          true),
    ("slider: effects volume",    "Effects Volume",        true),
    ("slider: percent readout",   " percent",              true),
    ("slider: music handle move", "length_mus",            true),
    ("slider: sfx handle move",   "length_sfx",            true),
    ("toggle: 3D sound state",    "sound_3D",              true),
    ("toggle: window size state", "window_small",          true),
    ("activation: user event",    "event_user(0)",         true),
    ("activation: mouse press",   "event_perform(ev_mouse",true),
    ("dialogue: repeat line",     "a11y_dlg_last, 1",      true),
    ("dialogue: enter advances",  "event_perform(ev_mouse, ev_global_left_press)", true),
    ("inventory: mode flag",      "a11y_inv",              true),
    ("inventory: I key",          "keyboard_check_pressed(ord(\"I\"))", true),
    ("inventory: item name",      ".name",                 true),
    ("inventory: active suffix",  "active_txt",            true),
    ("inventory: window follow",  "shift",                 true),
    ("inventory: count readout",  " of ",                  true),
    ("inventory: gui restored",   "show_gui = 1",          true),
    ("chapter: card text",        "a_cs.description",      true),
    ("chapter: enter advances",   "event_perform(ev_keypress, vk_space)", true),
    ("chapter: unlocked items",   "_text_chapter_end_unlocked", true),
    ("escape: backs out of inv",  "a_mk.a11y_inv = 0",    true),
    ("escape: closes info popup", "instance_find(Info, 0)", true),
    ("go back: by stored name",   "a_wtn == \"View_Back\"", true),
    ("go back: not by objindex",  "object_index == View_Back", false),
    ("skip set is parent-aware",  "ds_map_exists(a11y_skip", true),
    ("no exact Menu_Btn compare", "a_wo == Menu_Btn",     false),
    ("go back: no active guard",  "a_wt.active",          false),
    ("state: counter readout",    ", position ",          true),
    ("state: reread after press", "instance_exists(a_wt)", true),
    ("item use: valid target",    "USE ",                 true),
    ("item use: wrong item",      "takes an item, but not this one", true),
    ("item use: reads wrong_item","wrong_item = 0",       true),
    ("item use: holding readout", "Holding ",             true),
    ("needs-an-item wording",     "needs an item",        true),
    ("info: surface guard",       "surface_create(1024, 768)", true),
    ("info: enter closes",        "ev_global_left_press", true),
    ("info: transcriptions",      "CALL ME!! 555-279",    true),
    ("info: phone number 2",      "637-511",              true),
    ("info: patient card",        "Patient card.",        true),
    ("filter: A/D modes",         "a11y_w_mode",          true),
    ("filter: category map",      "a11y_cat",             true),
    ("filter: exits mode",        "Exits",                true),
    ("filter: scenery mode",      "Scenery",              true),
    ("gained: item pickup",       "added to your inventory", true),
    ("gained: status",            " gained.",             true),
    ("gained: pause guard",       "!instance_exists(Pause)", true),
    ("scene: focus by instance",  "a11y_w_id",            true),
    ("scene: no list signature",  "a11y_w_sig",           false),
    ("scene: room-change only",   "room != a11y_w_room",  true),
    ("status: screen handled",    "instance_exists(Status_Menu)", true),
    ("status: ending state",      "Good ending",          true),
    ("status: back button",       "Status_Menu_Resume",   true),
    ("scene: no visible filter",  "visible == 0",         false),
    ("scene: mask filter",        "sprite_index == -1",   true),
    ("scene: go back entry",      "Go back",              true),
    ("scene: go back room_goto",  "room_goto(a_wt.lvl_back)", true),
    ("health: wound status",      "Status_Wounds_Agony",  true),
    ("health: H key",             "keyboard_check_pressed(ord(\"H\"))", true),
    ("health: damage watch",      "Hurt. ",               true),
    ("scene: enumerates world",   "instance_number(Interactive_Object)", true),
    ("scene: excludes items",     "ds_map_exists(a_skip", true),
    // The ending screens. F4 used to count the persistent inventory as things standing in
    // the room, and the click that ends the game was in no list at all.
    ("F4: excludes items",        "ds_map_exists(a_dgsk", true),
    ("F4: excludes interface",    "ds_map_exists(a11y_skip, a_dgx.object_index)", true),
    ("F4: says nothing usable",   "Nothing in this room can be used", true),
    // Object references decompile numerically, so the ending controller cannot be checked
    // by name; the second ds_list_add into a11y_extra is it. And 53 comes back out of the
    // compiler as the named constant.
    ("ending: listed",            "\"The_End_Controller\"", true),
    ("ending: press confirmed",   "Ending the game.", true),
    ("ending: timer honoured",    "Let the ending play out first", true),
    ("ending: label",             "Finish, end the game", true),
    ("ending: picture",           "looking down the duvet at your own bare feet", true),
    ("ending: light told apart",  "The room is almost completely dark", true),
    // Pressing an entry used to act on it and say nothing: a screen reader cancels its
    // own speech when Enter goes down, so the announcement has to wait for the key.
    ("press: announcement held",  "a11y_wpend", true),
    ("press: waits for release",  "keyboard_check(vk_enter)", true),
    ("press: says it later",      "external_call(a11y_f_speak, a11y_wsay, 1)", true),
    // The mod's own settings screen, and the file it remembers itself in.
    ("settings: menu row",        "\"@a11y\"", true),
    ("settings: label",           "Accessibility settings", true),
    ("settings: warn row",        "Warn about danger", true),
    ("settings: hint row",        "Hints about what to use", true),
    ("settings: saved to file",   "A11y.ini", true),
    ("settings: warn gates hurt", "a11y_warn && ds_map_exists(a11y_hurt", true),
    ("settings: hint gates use",  "a_itc && a11y_hint", true),
    ("autosave announced",        "Game saved.", true),
    ("scene: hover probe",        "event_user(1)",        true),
    // The bridge sign. Its hover destroys it, so probing it killed the game; the probe
    // is now skipped for every object whose hover calls instance_destroy.
    ("hover: destroy set",        "ds_map_exists(a11y_nohover", true),
    ("hover: neutral fallback",   "a_cur = 36", true),
    ("scenery: guard nested",     "instance_exists(a_wt) && ds_map_exists", false),
    ("prox: guard nested",        "instance_exists(a_pi3) && ", false),
    ("scene: verb from cursor",   "locked",               true),
    ("scene: name prettified",    "string_replace_all",   true),
    ("scene: text_info restored", "text_info = a_sti",    true),
    // Checks the MECHANISM, not the spelling. This needle used to be
    // instance_exists(Worm_February) and went red the moment that guard was correctly
    // changed to guard the instance instead of the object.
    ("post-load recovery",        "instance_find(Worm_February, 0)", true),
    ("post-load schema tag",      "a_mk.friction ==",      true),
    ("marker guarded on instance", "instance_exists(a_mk)", true),
    ("recovery: no bad builtin",  "variable_local_exists", false),
    ("recovery: marker created",  "Worm_February)", true),
    ("recovery: marker persists", "persistent = true",     true),
    ("board: game-over said",  "The board game is over", true),
    ("board: die end state",   ", game over",          true),
    ("board: death state",     "return to the checkpoint", true),
    ("board: roll announced",  "Rolled ",              true),
    ("board: square announced","Square ",              true),
    ("board: die label",       "ready to roll",        true),
    ("board: piece label",     "Your piece, square ",  true),
    ("board: death warning",   "back to the checkpoint", true),
    ("phone: number keys",     "vk_numpad0 + a_d",     true),
    ("phone: reads dialled",   ".number",              true),
    ("phone: digits hidden",   "ds_map_exists(a11y_phone", true),
    ("phone: key wording",     ", key ",               true),
    ("collision re-evaluated", "place_meeting",        true),
    ("drag: paperclip placed",  "Bridge_06_Mask",       true),
    ("drag: announced",         "Paperclip moved into place", true),
    ("coin: electrified state", "electrified",          true),
    ("cursor warp on focus",     "window_mouse_set",     true),
    ("warp uses view scale",     "view_wview",           true),
    ("proximity targets listed", "@prox",                true),
    ("proximity: Bridge_Wire",   "a11y_prox",            true),
    ("schema tag guards marker",  "a_mk.friction ==",     true),
    ("schema tag written last",   "a11y_mk.friction =",   true),
    ("state: marker is authority", "a_mk.a11y_lbl",        true),
    ("state: hydrate from marker", "a11y_ready = a_mk.a11y_ready", true),
    ("state: persist to marker",   "a_mk.a11y_ready = a11y_ready", true),
    ("guard reads no Controller",  "ds_exists(a11y_lbl",   false),
    ("recovery: ownership stamp", "\"@a11y\"",             true),
    ("names: pretty map",        "a11y_pretty",           true),
    ("names: mask trimmed",      "ds_map_add(a11y_pretty", true),
    ("names: prox uses it",      "ds_map_find_value(a11y_pretty", true),
    ("lights: switch state",     "Hall light switch",     true),
    ("lights: elevator reason",  "the hall lights are off", true),
    ("wire: cable state",        "Computer cable",        true),
    ("wire: computer reason",    "the cable is unplugged", true),
    ("computer: family map",     "a11y_comp",             true),
    ("computer: window map",     "a11y_cwin",             true),
    ("computer: colour names",   "dark green",            true),
    ("computer: window spoken",  "Press Escape to close", true),
    ("computer: drawing done",   "The drawing is finished", true),
    ("computer: icon hint",      "press again to open",   true),
    ("computer: swatch listed",  "a11y_extra",            true),
    ("computer: synthetic press","event_perform(ev_mouse, ev_left_press)", true),
    ("computer: escape closes",  "Computer_Window_Opener", true),
    ("computer: orphan sweep",   "instance_exists(parent)", true),
    ("area: short-name map",     "a11y_short",            true),
    ("area: toggle flag",        "a11y_area",             true),
    ("area: F1 toggle",          "keyboard_check_pressed(vk_f1)", true),
    ("area: spoken state",       "Area names off",        true),
    ("clutter: map baked",       "a11y_clutter",          true),
    ("clutter: F2 toggle",       "keyboard_check_pressed(vk_f2)", true),
    ("clutter: spoken state",    "Clutter hidden",        true),
    ("repeat moved to F3",       "keyboard_check_pressed(vk_f3)", true),
    ("repeat no longer F1 only", "a11y_junk",             true),
    ("verb: pick up",            "pick up",               true),
    ("verb: pickup map",         "a11y_pick",             true),
    ("speech: queued when lost", "external_call(a11y_f_speak, a_wl, a_wint)", true),
    ("speech: not always 1",     "a_wint = 0",            true),
    ("speech: keys interrupt",   "a_wint = 1",            true),
    ("hazard: warning spoken",   "hurts you",             true),
    ("hazard: map baked",        "a11y_hurt",             true),
    ("pot: progress spoken",     "ingredients in",        true),
    ("pot: ready state",         "use the can on it",     true),
    ("leech: listed as prox",    "Forest_Leech",          true),
    ("leech: told to hold",      "stay here until it lets go", true),
    ("prox: hidden when unseen", "a_pi3.visible",         true),
    ("paint: 1 arms fill",       "Computer_Paint_Icon_FIll", true),
    ("paint: 2 arms take",       "Computer_Paint_Take_Color", true),
    ("paint: tool state said",   " selected.",            true),
    ("desk: icons map",          "a11y_desk",             true),
    ("desk: only with a window", "instance_exists(Computer_Window)", true),
    ("switch: light state",      "Flat_Hall_Light",       true),
    ("switch: curtain wording",  ", open",                true),
    ("switch: shower wording",   "running",               true),
    ("switch: billboard",        "Bridge_01_Sign_Light",  true),
    ("switch: drawer self read", "a_wt2.visible",         true),
    ("cutscene: announced",      "Nothing here can be used yet", true),
    ("cutscene: enter clicks",   "with (Cutscene)",       true),
    ("cutscene: state tracked",  "a11y_cut_last",         true),
    ("mirror: transporting",     "Transporting.",         true),
    ("mirror: transition map",   "a11y_trans",            true),
    ("board: hazard map",        "a11y_board",            true),
    ("board: square by nearest", "point_distance(a_bpi.x", true),
    ("board: deadly square",     ", DEADLY",              true),
    ("board: crossed out",       "crossed out",           true),
    ("board: corrections left",  "corrections left",      true),
    ("board: checkpoint said",   "a checkpoint",          true),
    ("board: space plays turn",  "Board_Dice_Roll) && !a11y_inv", true),
    ("board: space prompt",      "Press Space to move",   true),
    ("board: setup hint",        "The board is not set up", true),
    ("board: reroll cue",        "Enter on the die to reroll", true),
    ("board: ending warning",   "costs the good ending", true),
    ("mask: scream cutscene",   "The mask screams",      true),
    ("mask: clean rag said",    "needs the CLEAN rag",   true),
    ("mask: portrait blocked",  "blocked by the screaming mask", true),
    ("bin: paper is the door",  "Bin, look inside",      true),
    ("bin: rustle only",        "Bin, rustle it",        true),
    ("bin: pile not a pickup",  "nothing in it to take", true),
    ("bin: cleared said",       "Rubbish cleared out",   true),
    ("chapter: says press",     ". Press Enter to carry on.", true),
    ("F4: room report",         "keyboard_check_pressed(vk_f4)", true),
    ("F4: room name table",     "a11y_rooms",            true),
    ("F4: usable count",        " usable",               true),
    ("pics: table",             "a11y_pics",             true),
    ("pics: F5 repeat",         "keyboard_check_pressed(vk_f5)", true),
    ("pics: portrait text",     "Our Family",            true),
    ("pics: letter to death",   "Dear Death",            true),
    ("pics: cut state",         "cut out of the corner", true),
    ("pics: calendar 13",       "which reads thirteen",  true),
    ("pics: soda keypad",       "burnt black and unreadable", true),
    ("pics: bridge car",        "eyes drawn as crosses", true),
    ("pics: torn inventory",    "headed Inventory",      true),
    ("leech: percent full",     "percent full",          true),
    ("leech: let go said",      "The leech has let go",  true),
    ("cutscene: key only if 1",  "a_cut == 1",            true),
    ("letter: envelope state",   "no coin in it",         true),
    ("letter: address/stamp",    "not stamped",           true),
    ("letter: empty hands hint", "with nothing selected", true),
    ("item: held-cursor match",  "active_item.cursor_image", true),

    // Story events: the two sweeps, one row from each table, and the pause guard that
    // stops instance_deactivate_all replaying the whole story when a menu closes.
    ("event: appearance sweep",  "a11y_evon",             true),
    ("event: flag list",         "a11y_flgl",             true),
    ("event: one per frame",     "a_evsaid",              true),
    ("event: earthquake",        "The bridge shakes hard", true),
    ("event: bird takes hand",   "come round back in room 15", true),
    ("event: scarecrow",         "comes down off its post", true),
    ("event: morgue banging",    "hammering on the morgue door", true),
    ("event: doll crowbar",      "crowbar goes through the doll", true),
    ("event: patient fingers",   "take the patient's fingers off", true),
    ("event: zombie cut",        "off at the wrist",      true),
    ("event: eraser scarecrow",  "rubs the scarecrow out", true),
    ("event: pentagram",         "pentagram grinds aside", true),
    ("event: beehive",           "the hive goes up",      true),
    ("event: butcher in the wc", "locks behind him",      true),
    ("event: old man eats",      "The old man eats it",   true),
    ("event: stars counted",     "Star ",                 true),
    ("event: pause guard",       "instance_exists(Pause)", true),

    // Cutscenes: the key is only offered where a handler exists, and the old blanket
    // promise is gone.
    ("cut: key table",           "a11y_cutkey",           true),
    ("cut: neutral wording",     "Something is happening. Wait.", true),
    ("cut: no blanket offer",    "a_cut == 1 && a_cutk",  true),

    // The film in the VHS tape.
    ("tape: clown steps",        "a11y_nm_step",          true),
    ("tape: cuts the fish",      "He cuts the fish open", true),
    ("tape: kitchen picture",    "cartoon kitchen",       true),
    ("tape: room named",         "The tape, the kitchen", true),
    ("tape: colour bars",        "colour bars",           true),

    // The rest of this pass.
    ("mirror: butcher words",    "I am glad I could HELP", true),
    ("ticket: number said",      "Ticket, number 3",      true),
    ("ticket: item suffix",      "a11y_iname",            true),
    ("window: open or closed",   "Hospital_Hall_03_Window_Open", true),
    ("room: waiting renamed",    "Waiting room",          true),
    ("scenery: description map", "a11y_scn",              true),
    ("scenery: no repeat",       "a11y_scn_id",           true),
    ("scenery: re-arm on focus", "a11y_scn_id = 0",       true),
};

foreach (var (label, needle, want) in checks)
{
    bool found = all.Contains(needle);
    bool ok = found == want;
    Console.WriteLine($"  [{(ok ? "OK" : "!!")}] {label,-26} {(found ? "found" : "absent")}");
}
